### ISSUE TITLE
页面格式错乱怎么办

### ISSUE THREAD

**Issue by MoveCloudROY** [ZEROKISEKI/hexo-theme-cube#16]
![image](https://user-images.githubusercontent.com/32302164/43073450-3c0db5c2-8eac-11e8-94f5-b2a5f77bb785.png)

**Comment by MoveCloudROY** [comment]
@ZEROKISEKI 求助

**Comment by ghost** [comment]
清除浏览器缓存试一试

**Comment by MoveCloudROY** [comment]
额，其实已经解决了，我忘改config的site了。。。
