### ISSUE TITLE
歌词无法显示

### ISSUE THREAD

**Issue by justlooks** [ZEROKISEKI/hexo-theme-cube#2]
点击的时候显示not available

**Comment by ZEROKISEKI** [comment]
歌词无法显示是因为你用的地址是我的cdn 歌词地址，目前我的cdn只接受我那个域名的请求(设置了access-origin)，所以显示是not available

**Comment by justlooks** [comment]
但是即使我把歌词文件 放到github上去显示也是无法读取到
XMLHttpRequest cannot load https://github.com/justlooks/oldblogbak/blob/master/music/%E5%AE%B5%E9%97%87%E8%8A%B1%E7%81%AB.lrc. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://justlooks.github.io' is therefore not allowed access.

**Comment by ZEROKISEKI** [comment]
那是因为XMLHttpRequest只能是同域的请求，你放在了github上面，地址为[https://github.com/justlooks/oldblogbak/blob/master/music/%E5%AE%B5%E9%97%87%E8%8A%B1%E7%81%AB.lrc](https://github.com/justlooks/oldblogbak/blob/master/music/%E5%AE%B5%E9%97%87%E8%8A%B1%E7%81%AB.lrc)
但是你的博客地址为[https://justlooks.github.io](https://justlooks.github.io)，属于不同域，所以无效，对此的解决方式是：你可以把你的歌词放在你的github.io库中: 比如放在github.io库下的music文件中中，然后再`_config.yml`上进行设置:

```

    lrc: https://justlooks.github.io/lrc/xxx.lrc

```

**Comment by justlooks** [comment]
好像还是没用 ，还是被block了
script.js:1 Mixed Content: The page at 'https://justlooks.github.io/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://justlooks.github.io/oldblogbak/%E5%AE%B5%E9%97%87%E8%8A%B1%E7%81%AB.lrc'. This request has been blocked; the content must be served over HTTPS.
value @ script.js:1
e @ script.js:1
(anonymous) @ script.js:1
a @ script.js:1
(anonymous) @ script.js:1
e.(anonymous function) @ script.js:1
r @ script.js:1
(anonymous) @ script.js:1
t @ script.js:1
(anonymous) @ script.js:1
(anonymous) @ script.js:1
(anonymous) @ script.js:1
a @ script.js:1
(anonymous) @ script.js:1
e.(anonymous function) @ script.js:1
r @ script.js:1
(anonymous) @ script.js:1
t @ script.js:1
(anonymous) @ script.js:1
u @ script.js:1
p @ script.js:1
setTimeout (async)
(anonymous) @ script.js:1
c @ script.js:1
fireWith @ script.js:1
fire @ script.js:1
c @ script.js:1
fireWith @ script.js:1
ready @ script.js:1
u @ script.js:1
script.js:1 GET https://justlooks.github.io/content.json 404 ()

**Comment by ZEROKISEKI** [comment]
看错误提示，是你的github.io强制使用了https，所以要设置https的链接:

```
     
     'http://justlooks.github.io/oldblogbak/%E5%AE%B5%E9%97%87%E8%8A%B1%E7%81%AB.lrc'
     改为:
     'https://justlooks.github.io/oldblogbak/%E5%AE%B5%E9%97%87%E8%8A%B1%E7%81%AB.lrc'

```

你应该是在你github.io的repo库下setting 设置了force https

**Comment by justlooks** [comment]
但是如果我直接改成https ,试了下，取的请求都不会发了
只有出现这一个404失败
script.js:1 GET https://justlooks.github.io/content.json 404 ()

**Comment by ZEROKISEKI** [comment]
刚才看了一下，你的blog的歌词可以显示了(前面出现undefined是因为我那个歌词文件自己的内容就是写着undefined)。

然后出现你这个`content.json`的问题，我在文档中有提到了，是没有安装对应的依赖:

``` 

     npm install hexo-generator-json-content --save

```

这个需要在你的hexo站点的目录安装
然后在你的Hexo站点的_config.yml(非主题的_config.yml)上进行对应的设置:

```

jsonContent:
  pages:
    title: true
    text: true
    path: true
    preview: true
  posts:
    title: true
    text: true
    path: true
    preview: true

```

如果你不想用搜索功能，那么在你的主题下的`_config.yml`将那个`search`设置为false即可。

**Comment by justlooks** [comment]
可以了，谢谢！
