### ISSUE TITLE
代码段无法以前后滚动条来收纳，目前是全部显示，比较难看

### ISSUE THREAD

**Issue by justlooks** [ZEROKISEKI/hexo-theme-cube#3]
这个是markdown插件原因还是主题的问题？另外使用 codeblock语法显示代码块的标题有点问题，见下面的网址
https://justlooks.github.io/2017/08/31/kubernetes-Garbage-Collection/

**Comment by ZEROKISEKI** [comment]
感谢反馈！已修复该问题，可以在cube主题目录下进行pull后重新部署hexo，如有问题可继续在issue上反馈(虽然我可能无法马上看到23333)

**Comment by justlooks** [comment]
赞一下，标题考虑显示再美化一点，最好标题居中显示，像章鱼那种最好了
