### ISSUE TITLE
你好，发现一个主题挺好看的，能否移植到hexo？

### ISSUE THREAD

**Issue by jerry011235** [ZEROKISEKI/hexo-theme-cube#5]
你好，发现一个主题挺好看的，有空的话，能否移植到hexo？先谢谢了。
https://github.com/hi-caicai/farbox-theme-cais

**Comment by ZEROKISEKI** [comment]
可以，但估计下个月才有空着手弄个，repo到时放在这里[https://github.com/ZEROKISEKI/theme-cais](https://github.com/ZEROKISEKI/theme-cais)，可以关注下。
